Cue-Fit_Service_FrontEnd/final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('v1.urls')),
]

Cue-Fit_Service_FrontEnd/v1/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from v1.views import *
from . import views
from .views import combine_images_view

app_name = 'v1'

urlpatterns = [
    path('', index, name='index'),
    path('index.html', index, name='index'),
    path('index1.html', index1, name='index1'),
    path('about.html', about, name='about'),
    path('contact.html', contact, name='contact'),
    path('blog.html', blog, name='blog'),
    path('blog-details.html', blog_details, name='blog_details'),
    path('projects.html', projects, name='projects'),
    path('project2.html', project2, name='project2'),
    path('project-details.html', project_details, name='project_details'),
    path('services.html', services, name='services'),
    path('service2.html', service2, name='service2'),
    path('service3.html', service3, name='service3'),
    path('recomnend.html', recomnend, name='recomnend'),
    path('recommend.html', recommend, name='recommend'),
    path('upload-and-process_image', upload_and_process_image, name='upload_and_process_image'),
    path('combine_images_view', views.combine_images_view, name='combine_images_view'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cue-Fit_Service_FrontEnd/v1/models.py
from django.db import models

# Create your models here.

Cue-Fit_Service_FrontEnd/v1/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

Cue-Fit_Service_FrontEnd/v1/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.files.base import ContentFile
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from rembg import remove
from PIL import Image
import numpy as np
from django.conf import settings

# Create your views here.

def index(request):
    return render(request, 'index.html')

def index1(request):
    return render(request, 'index1.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def blog(request):
    return render(request, 'blog.html')

def blog_details(request):
    return render(request, 'blog-details.html')

def projects(request):
    return render(request, 'projects.html')

def project2(request):
    return render(request, 'project2.html')

def project_details(request):
    return render(request, 'project-details.html')

def services(request):
    return render(request, 'services.html')

def service2(request):
    return render(request, 'service2.html')

def service3(request):
    return render(request, 'service3.html')

def recomnend(request):
    return render(request, 'recomnend.html')

def recommend(request):
    return render(request, 'recommend.html')

from django.shortcuts import render
from .forms import ImageUploadForm
from .utils import remove_background
import os
from django.conf import settings

def upload_and_process_image(request):
    form = ImageUploadForm()
    output_image_url = None  # 초기화

    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']
            image_path = os.path.join(settings.MEDIA_ROOT, image.name)
            output_image_path = os.path.join(settings.MEDIA_ROOT, 'processed', image.name)
            
            # 이미지 파일 저장
            with open(image_path, 'wb+') as destination:
                for chunk in image.chunks():
                    destination.write(chunk)

            # 배경 제거 처리
            remove_background(image_path, output_image_path)

            # 결과 이미지 URL
            output_image_url = settings.MEDIA_URL + 'processed/' + image.name

            return render(request, 'projects.html', 
                          {'form': form, 
                           'output_image_url': output_image_url})

    else:
        form = ImageUploadForm()
        return render(request, 'projects.html', {'form': form})



from django.http import JsonResponse
from django.conf import settings
from .combine import load_and_blend_images, save_combined_image
import os
from datetime import datetime

def combine_images_view(request):
    if request.method == 'POST':
        foreground_image = request.FILES['foreground']
        background_image = request.FILES['background']

        # 파일을 임시 저장
        foreground_path = os.path.join(settings.MEDIA_ROOT, 'processed', foreground_image.name)
        background_path = os.path.join(settings.MEDIA_ROOT,  'processed', background_image.name)
        with open(foreground_path, 'wb+') as f:
            for chunk in foreground_image.chunks():
                f.write(chunk)
        with open(background_path, 'wb+') as f:
            for chunk in background_image.chunks():
                f.write(chunk)

        # 이미지 합성
        result_image = load_and_blend_images(foreground_path, background_path)

        # 결과 이미지 저장 및 URL 생성
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        result_image_name = f"result_{timestamp}.png"
        output_path = os.path.join(settings.MEDIA_ROOT, 'processed', result_image_name)
        save_combined_image(result_image, output_path)
        combined_image_url = os.path.join(settings.MEDIA_URL, 'processed', result_image_name)

        # 결과 이미지 URL을 템플릿에 전달
        return render(request, 'project2.html', {'combined_image_url': combined_image_url})

    else:
        return render(request, 'project.html')

Cue-Fit_Service_FrontEnd/v1/templates/project2.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .image-preview {
            width: 100%;
            height: 500px;
            border: 2px dashed #e2e8f0;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            color: #8b6464;
            background-size: cover;
            background-position: center;
        }
    </style>
  
  <title>Cue-Fit 오운완 이미지 생성</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/img/favicon.png" rel="icon">
  <link href="/static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Roboto:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Work+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="/static/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: UpConstruction
  * Updated: Sep 18 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/upconstruction-bootstrap-construction-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="/static/img/logo.png" alt=""> -->
        <h1>Cue-Fit<span>.</span></h1>
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="index.html" class="active">홈</a></li>
          <li><a href="services.html">Cue-Fit 헬스장 추천</a></li>
          <li><a href="projects.html">오운완 이미지 생성</a></li>
        </ul>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('/static/img/dalle11.png');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>오운완 이미지 생성</h2>
        <ol>
          <li>오늘 운동 완료(오운완) 이미지 생성 및 합성 서비스</li>
        </ol>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Our Projects Section ======= -->
    <section id="project2" class="project2">
      <div class="container mx-auto p-4">
          <div class="section-header">
              <h2>오운완 이미지 합성</h2>
              <p>원하시는 사진을 합성해서 나만의 오운완을 만들어보세요!</p>
          </div>

          <form method="post" enctype="multipart/form-data" action="{% url 'v1:combine_images_view' %}">
              {% csrf_token %}
              <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <!-- Image 1 Upload -->
                  <div>
                      <div class="p-8 border border-gray-200 rounded">
                          <h2 class="font-bold mb-4" style="font-size: 20px;">회원님의 사진을 업로드해주세요!</h2>
                          <input type="file" name="foreground" class="mb-4" accept="image/*" onchange="loadImage(event, 'preview1')">
                          <div id="preview1" class="image-preview">배경 제거 이미지</div>
                      </div>
                  </div>

                  <!-- Image 2 Upload -->
                  <div>
                      <div class="p-8 border border-gray-200 rounded">
                          <h2 class="font-bold mb-4" style="font-size: 20px;">생성한 배경 이미지를 업로드해주세요!</h2>
                          <input type="file" name="background" class="mb-4" accept="image/*" onchange="loadImage(event, 'preview2')">
                          <div id="preview2" class="image-preview">Dall E 배경 이미지</div>
                      </div>
                  </div>

                  <!-- Submit Button -->
                  <div>
                      <div class="p-8 border border-gray-200 rounded">
                          <h2 class="font-semibold mb-2" style="font-size: 20px;">버튼을 눌러 이미지를 합성해주세요!</h2>
                          <button type="submit" class="bg-yellow-500 hover:bg-blue-700 text-black font-bold py-2 px-4 rounded mb-4" style="font-size: 20px;">오운완 생성하기!</button>
                          <div id="combinedPreview" class="image-preview">
                            {% if combined_image_url %}
                            <img src="{{ combined_image_url }}" alt="Processed Image" style="max-width:100%; height: 100%">
                            {% else %}
                            오운완 이미지가 여기에 생성됩니다
                            {% endif %}
                          </div>
                      </div>
                  </div>
              </div>
          </form>
      </div>
      <script>
        function loadImage(event, previewId) {
            const output = document.getElementById(previewId);
            output.style.backgroundImage = `url(${URL.createObjectURL(event.target.files[0])})`;
            output.textContent = '';
        }
    </script>
    </section>
    <!-- End Our Projects Section -->


  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content position-relative">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <h3>Cue-Fit</h3>
              <p>
                아시아경제 교육센터<br>
                서울 중구 퇴계로 166<br><br>
                <strong>연락처:</strong> +82 010-1004-1004<br>
                <strong>이메일:</strong> cufit@gmail.com<br>
              </p>
            </div>
          </div><!-- End footer info column-->

          <div class="col-lg-2 col-md-3 footer-links">
            <h4>Cue-Fit 정보</h4>
            <ul>
              <li><a href="#"></a></li>
              <li><a href="#">BEST 서비스</a></li>
              <li><a href="#">BEST PT</a></li>
              <li><a href="#">BEST 시설</a></li>
            </ul>
          </div><!-- End footer links column-->

          <div class="col-lg-2 col-md-3 footer-links">
            <h4>헬스장 추천 서비스</h4>
            <ul>
              <li><a href="#"></a></li>
              <li><a href="#">헬스장 추천</a></li>
            </ul>
          </div><!-- End footer links column-->

          <div class="col-lg-2 col-md-3 footer-links">
            <h4>오운완 이미지 생성</h4>
            <ul>
              <li><a href="#"></a></li>
              <li><a href="#">Dall E 이미지 생성</a></li>
              <li><a href="#">사용자 이미지 배경 제거</a></li>
              <li><a href="#">이미지 합성</a></li>
            </ul>
          </div><!-- End footer links column-->

        </div>
      </div>
    </div>

    <div class="footer-legal text-center position-relative">
      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>Cue-Fit</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/upconstruction-bootstrap-construction-website-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </div>

  </footer>
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/vendor/aos/aos.js"></script>
  <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="/static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/js/main.js"></script>
  <script src="/static/js/dalle.js"></script>

</body>

</html>

Cue-Fit_Service_FrontEnd/v1/templates/projects.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
  <title>Cue-Fit 오운완 이미지 생성</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/img/favicon.png" rel="icon">
  <link href="/static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Roboto:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Work+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="/static/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: UpConstruction
  * Updated: Sep 18 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/upconstruction-bootstrap-construction-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="/static/img/logo.png" alt=""> -->
        <h1>Cue-Fit<span>.</span></h1>
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="index.html" class="active">홈</a></li>
          <li><a href="services.html">Cue-Fit 헬스장 추천</a></li>
          <li><a href="projects.html">오운완 이미지 생성</a></li>
        </ul>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('/static/img/dalle11.png');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>오운완 이미지 생성</h2>
        <ol>
          <li>오늘 운동 완료(오운완) 이미지 생성 및 합성 서비스</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Our Projects Section ======= -->
    <section id="projects" class="projects">
      <div class="container" data-aos="fade-up">
        <div class="section-header">
          <h2>사용자 이미지 배경 제거 및 배경 생성</h2>
          <p>본인의 사진을 배경 제거하고 Dall-E를 이용해서 배경 이미지를 생성해보세요!</p>
        </div>
        {% csrf_token %}
        <div class="row">
          <!-- 사용자 사진 업로드 컬럼 -->
          <div class="col-lg-6 col-md-6">
            <form id="image-upload-form" class="form-inline" method="post" enctype="multipart/form-data" action="{% url 'v1:upload_and_process_image' %}">
              {% csrf_token %}
              <!-- 이미지 업로드 입력 폼 -->
              <div class="form-group mb-2">
                <label for="image-upload" class="form-label" style="font-size: 24px;"><strong>본인의 사진 첨부:</strong></label>
                <p>본인이 나온 사진을 첨부해주세요! 배경을 제거해서 합성해드릴게요</p>
                
                <input type="file" id="image-upload" name="image" class="form-control mb-4" accept="image/*">
                <button type="submit" id="remove-bg-button" class="btn btn-secondary mb-4">배경 제거하기</button>
              </div>
            </form>
            <div id="uploaded-image" style="margin-bottom: 30px; text-align: center;">
              {% if output_image_url %}
                <img src="{{ output_image_url }}" alt="Processed Image" style="max-width:100%;">
              {% endif %}
            </div>
          </div>
          <!-- DALL-E 이미지 생성 폼 컬럼 -->
          <div class="col-lg-6 col-md-6">
            <form id="dalle-form" class="form-inline">
              <!-- 이미지 설명 입력 폼 -->
              <div class="form-group mb-2">
                <label for="prompt" class="form-label"style="font-size: 24px;"><strong>Cue-Fit (Dall-E 활용) 배경 이미지 생성 Tip!</strong></label>
                <p>원하는 배경 입력은 자세하게 부탁드립니다!</p>
              </div>
              <input type="text" id="prompt" class="form-control mb-4" placeholder="이미지에 대한 설명을 영어로 입력해주세요">
              <button type="submit" class="btn btn-primary mb-4">생성하기</button>
              <button type="button" id="next" class="btn btn-primary mb-4" onclick="redirectToProject2()">다음</button>
            </form>
            <div id="generated-image">
              <!-- DALL-E에 의해 생성된 이미지가 여기에 표시됩니다 -->
            </div>
          </div>
        </div>
      </div>
    </section>
    <script>
      // '다음' 버튼 클릭 시 project2.html 페이지로 리다이렉트
      function redirectToProject2() {
        window.location.href = '/project2.html';
      }
    </script>
<!-- End Our Projects Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content position-relative">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <h3>Cue-Fit</h3>
              <p>
                아시아경제 교육센터<br>
                서울 중구 퇴계로 166<br><br>
                <strong>연락처:</strong> +82 010-1004-1004<br>
                <strong>이메일:</strong> cufit@gmail.com<br>
              </p>
            </div>
          </div><!-- End footer info column-->

          <div class="col-lg-2 col-md-3 footer-links">
            <h4>Cue-Fit 정보</h4>
            <ul>
              <li><a href="#"></a></li>
              <li><a href="#">BEST 서비스</a></li>
              <li><a href="#">BEST PT</a></li>
              <li><a href="#">BEST 시설</a></li>
            </ul>
          </div><!-- End footer links column-->

          <div class="col-lg-2 col-md-3 footer-links">
            <h4>헬스장 추천 서비스</h4>
            <ul>
              <li><a href="#"></a></li>
              <li><a href="#">헬스장 추천</a></li>
            </ul>
          </div><!-- End footer links column-->

          <div class="col-lg-2 col-md-3 footer-links">
            <h4>오운완 이미지 생성</h4>
            <ul>
              <li><a href="#"></a></li>
              <li><a href="#">Dall E 이미지 생성</a></li>
              <li><a href="#">사용자 이미지 배경 제거</a></li>
              <li><a href="#">이미지 합성</a></li>
            </ul>
          </div><!-- End footer links column-->

        </div>
      </div>
    </div>

    <div class="footer-legal text-center position-relative">
      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>Cue-Fit</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/upconstruction-bootstrap-construction-website-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </div>

  </footer>
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/vendor/aos/aos.js"></script>
  <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="/static/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/js/main.js"></script>
  <script src="/static/js/dalle.js"></script>

</body>

</html>